[package]
name = "stdin_handler"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.30.1", features = ["term"] }

[lib]
name = "stdin_handler"
crate-type = ["rlib", "cdylib", "staticlib"]